CFLAGS+=-D_FILE_OFFSET_BITS=64 -D_GUN_SOURCE -Wall

# # 定义变量SRC，表示源文件名
# SRC = $(wildcard $(filename).c)

# # 定义变量OBJ，表示目标文件名（.o文件）
# OBJ = $(patsubst %.c,%.o,$(SRC))

# # 默认目标：编译可执行文件
# all: $(filename)

# # 编译可执行文件
# $(filename): $(OBJ)
# 	gcc -o $@ $^

# # 编译目标文件
# %.o: %.c
# 	gcc -c -o $@ $<

# # 清理中间文件和可执行文件S
# clean:
# 	rm -f $(OBJ) $(filename)
